Tresjs/tres

package.json
playground/src/components/TheExperience.vue
playground/tsconfig.json

fix: package exports types

---

playground/src/components/TheSphere.vue
src/components/TresScene.ts
src/composables/useRenderer/index.ts

fix: re-mount custom renderer manually on HMR

---

CONTRIBUTING.md
docs/.vitepress/theme/config.css

I added proper colors for buttons in both dark and light modes, ensuring good contrast.
and fixed the broken link for the banner image in the contributor.md.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/Tresjs/tres/assets/40598819/6085f729-af55-4ca4-acd5-52fb1cb3f7a7" alt="Before: whytresold"></td>
<td><img src="https://github.com/Tresjs/tres/assets/40598819/0f37f56a-9338-4379-9adc-75a9f1192bb4" alt="After: whytresnew"></td>
</tr>
<tr>
<td><img src="https://github.com/Tresjs/tres/assets/40598819/8a41b967-76f2-40b3-828e-2d2560d999d7" alt="Before: startold"></td>
<td><img src="https://github.com/Tresjs/tres/assets/40598819/92b89199-1360-455f-b83a-bf7b82b9032c" alt="After: startnew"></td>
</tr>
</table>

fix: button color and banner image

---

docs/.vitepress/config.ts
docs/_data/team.js
docs/team.md
package.json
pnpm-lock.yaml

docs: add core team page

---

src/types/index.ts

fix: fake a `VNodeRef` on types to accept strings and null

---

pnpm-lock.yaml
src/composables/useRenderer/index.ts
src/core/revision.ts

fix: added revision version to apply useLegacyLights only if neccesary

---

src/components/TresCanvas.vue
src/core/renderer.ts

fix: 317 devtools

---

CHANGELOG.md
package.json
playground/src/components/TestSphere.vue
src/components/TresCanvas.vue

This might solve https://github.com/Tresjs/nuxt/issues/33

fix: proxy app context

---

playground/package.json
playground/src/pages/index.vue
pnpm-lock.yaml
src/core/nodeOps.ts

fix: ensure scene as parent fallback for helpers

---

docs/.vitepress/config.ts
docs/advanced/primitive.md
docs/examples/load-models.md

docs: added primitive

---

docs/.vitepress/config.ts

Please add.
I don't want to search twice :(

docs: Add github & issuess to top menu

---

src/components/TresCanvas.vue

Yeah, not giving any value anyway

feat: remove default camera warning

---

playground/src/components/TheExperience.vue
src/composables/useRenderer/const.ts
src/composables/useRenderer/index.ts

feat: 492 set tone mapping default to acesfilmictonemapping

---

components.d.ts
composables.d.ts
package.json
src/composables/useLoader/index.ts
src/composables/useRaycaster/index.ts
src/composables/useSeek/index.ts
types.d.ts
utils.d.ts

fix: correct type exporting issues

---

.github/workflows/actions/pnpm/action.yml
.husky/install.mjs
.husky/pre-push
package.json
pnpm-lock.yaml

chore: add pre-push linter hook

---

docs/.vitepress/theme/components/HomeSponsors.vue
docs/.vitepress/theme/custom.css
docs/package.json
docs/vite.config.ts
pnpm-lock.yaml

docs: sponsor friends

---

CONTRIBUTING.md

modify the `Setup` chapter in `CONTRIBUTING.md`

chore: modify `PnPM` to `Pnpm`

---

docs/.vitepress/config/fr.ts
docs/de/guide/index.md
docs/fr/guide/index.md
docs/guide/index.md

Closes #676 
Fixes broken play/lab links in the docs site.

docs: fix play/lab links

---

src/utils/index.ts

fix: 682 helpers diposal error since latest threejs update `dispose` methods

---

package.json
pnpm-lock.yaml
src/types/index.ts

Based on https://github.com/vuejs/language-tools/issues/4170#issuecomment-2025528945 this will fix the issue with types on https://github.com/Tresjs/nuxt

fix: augmenting types for tres components for the nuxt module

---

playground/src/pages/events/FpsDropsReproduction.vue
playground/src/router/routes/events.ts
src/composables/useRaycaster/index.ts
src/core/nodeOps.ts

Possibly improves performance
Close #711

fix: intersect only objects with events registered.

---

src/core/nodeOps.test.ts

This PR adds some failing tests for `nodeOps` `insert` and `remove`.
They check:
* `insert`ing a `primitive` does not change a Mesh/Material/Geometry uuid
* `remove` does detach a `primitive` `object` but not its children
* `remove` does not dispose a `primitive` `object` or its children
* `remove` does not dispose a `<Tres[any] :dispose="null" />` or elements in its subtree
The failing tests are currently `skip`ped.

test: add insert/remove tests

---

src/composables/useTresContextProvider/index.ts
src/devtools/plugin.ts
src/index.ts
src/types/index.ts

This PR is also scoped to solve cientos typescript issues

fix: typescript issues

---

playground/src/pages/basic/index.vue
playground/src/pages/issues/796/TheBox.vue
playground/src/pages/issues/796/TheExperience.vue
playground/src/pages/issues/796/index.vue
playground/src/router/routes/issues.ts
src/components/TresCanvas.vue

fix: 796 unmount the canvas component instant mount children again even if canvas is not mounted

---

.github/workflows/pkg.pr.new.yml
package.json
pnpm-lock.yaml

Adds https://github.com/stackblitz-labs/pkg.pr.new 😊 
I think this will be a huge quality-of-life improvement for the tres ecosystem.

ci: add pkg.pr.new

---

src/core/nodeOps.test.ts
src/core/nodeOps.ts

This is a small reversion for 80f8a2e.
Closes #827

revert: add check for null props

---

src/composables/useLoader/index.ts

fix(function typo): fix typo in function name in composable

---

docs/advanced/attach.md
playground/vue/src/pages/advanced/attachBufferGeometry/index.vue
playground/vue/src/pages/advanced/attachPostProcessing/index.vue

This PR makes some minor rewording fixes to the `attach` docs and playgrounds.

docs(attach): rewording

---

docs/.vitepress/config/shared.ts
docs/.vitepress/theme/index.ts
docs/de/guide/getting-started.md
docs/de/guide/index.md
docs/de/guide/nuxt.md
docs/de/guide/troubleshooting.md
docs/es/guide/getting-started.md
docs/es/guide/index.md
docs/es/guide/nuxt.md
docs/es/guide/troubleshooting.md
docs/fr/guide/getting-started.md
docs/fr/guide/index.md
docs/fr/guide/nuxt.md
docs/fr/guide/troubleshooting.md
docs/guide/getting-started.md
docs/guide/index.md
docs/guide/nuxt.md
docs/guide/troubleshooting.md
docs/nl/guide/getting-started.md
docs/nl/guide/index.md
docs/nl/guide/nuxt.md
docs/nl/guide/troubleshooting.md
docs/package.json
docs/vite.config.ts
docs/zh/guide/getting-started.md
docs/zh/guide/index.md
docs/zh/guide/nuxt.md
docs/zh/guide/troubleshooting.md
pnpm-lock.yaml

This PR add [vitepress-plugin-group-icons](https://github.com/yuyinws/vitepress-plugin-group-icons) to enhance the document's readability.
---
---

docs: add `vitepress-plugin-group-icons`

---

src/composables/index.ts
src/composables/useLoader/index.ts
src/composables/useRenderer/index.ts
src/composables/useSeek/index.ts
src/core/nodeOps.ts
src/directives/vDistanceTo.ts
src/directives/vLightHelper.ts
src/utils/index.ts
src/utils/logger.ts

- Removed useLogger imports from various composables and directives.
- Introduced logError and logWarning functions from the new logger utility.
- Updated relevant code to utilize the new logging methods for improved clarity and maintainability.

chore: replace useLogger with logger utility functions

---

docs/_data/team.js
docs/team.md

Updated the teams page to reflect the latest updates from: https://github.com/Tresjs/.github/blob/main/MEMBERS.md

docs: update social and sponsor links for the team members

---

docs/fr/guide/index.md

This PR should fix #678 and address the missed section in French which was partially fixed in #645 
~~I will double-check my French translation.~~ 
Corrected and reviewed the french translations

docs: fix missing documentation for lab section in french docs

---

playground/vue/src/pages/events/index.vue
src/composables/useTresContextProvider/index.ts
src/devtools/plugin.ts
src/devtools/setupDevtools.ts
src/utils/perf.ts

- Added a new `setupDevtools` function to manage performance metrics such as FPS and memory usage.
- Integrated the `setupDevtools` function into the `useTresContextProvider` to enhance the development experience.
- Updated the `index.vue` page to utilize the `useControls` for FPS graphing.
- Cleaned up unused performance-related code to streamline the context provider logic.

feat: 974-createsetup-devtools

---

docs/contribute/contributing.md
playground/vue/components.d.ts
playground/vue/src/components/LocalOrbitControls.vue
playground/vue/src/pages/basic/PiercedProps.vue
src/core/nodeOps.ts

Closes #1010 
@CodyJasonBennett we just needed to camelCase the key at the end

fix: make sure key is camelCase when reached else on conditional

---

docs/.vitepress/config/en.ts
docs/advanced/performance.md
docs/composables/use-tres.md
playground/vue/src/pages/advanced/fbo/useFBO.ts
playground/vue/src/pages/advanced/manual/experience.vue
playground/vue/src/pages/advanced/on-demand/experience.vue
src/composables/index.ts
src/composables/useRenderer/useRendererManager.ts
src/composables/useTres/index.ts
src/composables/useTresContextProvider/index.ts
src/devtools/setupDevtools.ts

- Added the `useTres` composable to provide a simplified API for accessing the TresJS context, including methods for `invalidate` and `advance`.
- Updated various components and documentation to utilize the new `useTres` composable, enhancing code clarity and maintainability.
- Included a new documentation page for `useTres` detailing its usage and properties.

feat: introduce useTres composable and update related documentation

---

docs/app/components/AppHeader.vue
docs/app/pages/[...slug].vue
docs/content/3.api/1.index.md
docs/package.json
pnpm-lock.yaml

- Upgraded TypeScript and various dependencies in `pnpm-lock.yaml` and `package.json` to ensure compatibility with the latest features and improvements.
- Enhanced the `AppHeader.vue` component for better responsive design by adding a class to control visibility on different screen sizes.
- Updated documentation links and metadata in `index.md` to reflect new features and improve user navigation.
- Refactored the `useTres` composable documentation to clarify its usage context within the TresCanvas component, enhancing user understanding.

docs: nuxt 4

---

CONTRIBUTING.md

- Introduced a comprehensive contributing guide for TresJS, detailing the monorepo structure, development setup, workflow, code style guidelines, testing procedures, and pull request process.
- Aimed at enhancing collaboration and ensuring consistency in contributions.
Closes TRES-171

docs: add CONTRIBUTING.md to guide new contributors
