Tresjs/tres

src/composables/useRenderer/index.ts

I added a timeout is the fastest way to solve this issue, but also I changed the DOM element to the current canvas (not to the container) 
This because you can use something like
canvas{
position: absolute
height: 100vh
...
}
And render the scene but, the log appears because the container has 0 height
let me know
close #263

fix: message canvas 0 height false positives

---

docs/guide/migration-guide.md
docs/guide/troubleshooting.md
docs/guide/your-first-scene.md
playground/src/components/TheEvents.vue
src/components/TresScene.ts
src/core/nodeOps.ts

Following the issue of the state being used on nodeOps. I removed the `useCamera` logic from there.
I also improved the error handling. If the user doesn't pass a camera via slots or props, a default `PerspectiveCamera` will be created.
Closes #307 
Closes #302
Closes #273

feat: removed `useCamera` logic from nodeOps

---

docs/api/composables.md

There was an obvious error in one of the examples that is fixed in this PR.
Just a simple copypaste error probably :)

docs: fix error in example code

---

playground/src/components/DebugUI.vue
src/core/nodeOps.ts
src/utils/index.ts

fix: added logic on pathProps to re-instance nodes once `args` change

---

src/composables/useTexture/index.ts
src/utils/index.ts

Correctly infer the return type based on the argument.
Note: I would personally have accepted a single string rather than `[string]` to build a single `Texture` but that would be a breaking change

fix(types): useTexture()

---

package.json

In other project ecosystems, there may be compile-time reference errors.
` vite.config.ts `
import { templateCompilerOptions } from '@tresjs/core' 
so this part is added

chore: add package.json -> exports.require = "./dist/tres.umd.cjs"

---

docs/api/composables.md
src/composables/useSeek/index.ts

This implements [#236](https://github.com/Tresjs/cientos/issues/263)
Tldr; `seekAll` and `seekAllByName` are the same as `seek` and `seekByName` except that they return an array of all matches instead of the first match.
Both methods return an empty array `[]` when there are no matches

feat(useSeek): Add `seekAll` and `seekAllByName` methods to `useSeek` composable

---

playground/package.json
playground/src/pages/empty.vue
playground/src/pages/perf/AkuAku.vue
playground/src/pages/perf/index.vue
playground/src/router.ts
pnpm-lock.yaml
src/components/TresCanvas.vue
src/composables/useTresContextProvider/index.ts
src/core/nodeOps.ts

Closes #449 
- Forces memory free when disposing materials and geometries
- exposes hard `dispose` method

fix: force memory free allocation when disposing materials and geomeries

---

src/composables/useTresContextProvider/index.ts

Solved this issue (#511)
By minimizing the scene reproduction, I found that the real cause of jitter during rendering is the use of the two APIs `useElementSize` / `useWindowSize`. 
They both use the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) API, which is always a few milliseconds slower than the triggering of the onResize event. 
I also compared the behavior of R3F when resizing and found that there is an anti shake operation. 
Therefore, we only need to perform an anti-shake operation on the width and height values ​​to solve the problem.

fix(usetrescontextprovider): fixed rendering issues caused when resize is triggered

---

docs/guide/index.md

Closes #518
When running `pnpm run docs:dev` a warning was being printed to the terminal about an image path:
```
5:05:06 PM [vitepress] hmr update /guide/index.md
Assets in public directory cannot be imported from JavaScript.
If you intend to import that asset, put the file in the src directory, and use /src/playground.png instead of /public/playground.png.
If you intend to use the URL of that asset, use /playground.png?url.
Files in the public directory are served at the root path.
Instead of /public/playground.png, use /playground.png.
```
This updates the image path to remove the warning.

docs: change image path to silence warning, #518 

---

docs/.vitepress/config.ts
docs/.vitepress/theme/components/BlenderCube.vue
docs/.vitepress/theme/components/GraphPane.vue
docs/.vitepress/theme/components/OnDemandRendering.vue
docs/.vitepress/theme/components/RenderingLogger.vue
docs/.vitepress/theme/composables/state.ts
docs/advanced/performance.md
docs/api/composables.md
docs/api/tres-canvas.md
docs/components.d.ts
docs/package.json
playground/src/pages/rendering-modes/index.vue
playground/src/pages/rendering-modes/scene.vue
playground/src/router.ts
pnpm-lock.yaml
src/components/TresCanvas.vue
src/composables/useRenderer/index.ts
src/composables/useTresContextProvider/index.ts
src/core/nodeOps.ts
src/devtools/plugin.ts

This PR introduces the concept of conditional rendering. It closes #140
The `renderMode` prop has been added to the `TresCanvas` component with 3 different options:
- `always` the default one (current solution)
- `on-demand` will automatically invalidate the frame on:
- Instances prop changes
- Context state change (resize, clearColor etc)
- remove nodes (v-if)
- `manual`:  the `invalidate` method needs to be called by the user to trigger a render.
TresCanvas now emits a `render` event:
```
<TresCanvas
render-mode="on-demand"
clear-color="#82DBC5"
@render="onRender"
>
```
I'm still finishing the docs, you can start taking a look to it.

feat: 140 on demand rendering

---

src/composables/useSizes/index.ts
src/composables/useTresContextProvider/index.ts

Attempting to simplify the logic related to `sizes` and extract it into `useSizes` for easier maintenance in the future.

refactor: Simplify the logic for calculating sizes and extract it into useSizes

---

docs/api/composables.md

Came across a TypeScript error when tyring out this example from the docs, turns out `dt` no longer exists as return value from `onLoop`.

docs: removed non-existing return value from onLoop example

---

playground/src/pages/cameras/Cameras.vue
src/composables/useCamera/index.ts

Orthographic camera is not getting updates when screen size changes. So the aspect ratio falls out of sync with window size, resulting in squished/stretched images.
* Update orthographic camera aspect when screen size updates
* Give user a "manual" flag to keep Tres from updating camera
[Manual flag in R3F.](https://github.com/pmndrs/react-three-fiber/blob/0ef66a1d23bf16ecd457dde92b0517ceec9861c5/packages/fiber/src/core/utils.ts#L457)

fix: camera aspect

---

docs/cookbook/shaders.md

Appropriate TresShaderMaterial properties added to example code.

docs(cookbook): Update shaders.md

---

src/core/nodeOps.ts

fix: refactor nodeOps to return methods at the end of the function

---

playground/src/pages/basic/PiercedProps.vue
playground/src/router/routes/basic.ts
src/core/nodeOps.ts
src/core/nodeOpts.test.ts

Closes #605 for `v4`.
#203 added support for pierced props like `:position-x="10"`. It added this line:
https://github.com/Tresjs/tres/blob/98109af7d501da1ae5f817e7dc61c6d6ad902891/src/core/nodeOps.ts#L227
`:position-x="10"` works without lowercasing. 
`toLowerCase()` was removed to keep prop casing intact.
Pushing to `v4` as it's a breaking change: users who previously wrote e.g., `:position-X="10"` will find their code broken.
* `position-x` has [test coverage.](https://github.com/Tresjs/tres/blob/98109af7d501da1ae5f817e7dc61c6d6ad902891/src/core/nodeOpts.test.ts#L145) Existing test passes.
* An additional test was added for shader/material `defines`, as in #605 .
A playground for pierced props was added at /basic/pierced-props

fix: do not lowercase pierced props

---

docs/debug/devtools.md

A small change to the docs' devtools' intro text, as discussed on Discord.

docs: change devtools intro wording

---

docs/.vitepress/config/de.ts
docs/.vitepress/config/en.ts
docs/.vitepress/config/es.ts
docs/.vitepress/config/fr.ts
docs/.vitepress/config/nl.ts
docs/.vitepress/config/zh.ts

When clicking on **Suggest changes to this page** anywhere in the docs, it redirects to a "404 Not Found" page.
[Suggest changes to this page](https://github.com/tresjs/tres/edit/main/packages/docs/guide/index.md)
link from https://docs.tresjs.org/guide/ page.
https://github.com/Tresjs/tres/assets/858917/693ed540-b75c-4b24-a727-56705e3278bb

docs: fixed link to suggesting changes in docs

---

playground/src/pages/basic/OnCallbacks.vue
playground/src/router/routes/basic.ts
src/core/nodeOps.test.ts
src/core/nodeOps.ts

`on*` callbacks – e.g., `onBeforeRender` – are methods on THREE Objects. In plain THREE, these can be overridden by users. 
Currently in TresJS, a prop like `on-before-render="..."` calls the default function – which does nothing:
* https://github.com/mrdoob/three.js/blob/a2e9ee8204b67f9dca79f48cf620a34a05aa8126/src/materials/Material.js#L105
* https://github.com/mrdoob/three.js/blob/a2e9ee8204b67f9dca79f48cf620a34a05aa8126/src/core/Object3D.js#L123
It should instead *set* the function.
Add a predicate in `src/core/nodeOps.ts` where, for `prop-name="value"`:
* `prop-name` starts with `on`
* `object[propName]` is a function
* `value` is a function
In this limited case, `value` will replace `object[propName]`.
A unit test and a playground were also added.
This is a more targeted approach …

fix: make on* callbacks settable

---

src/composables/useTresEventManager/index.ts

This change fixes an oversight where we were not using the previous intersection event data for an @pointer-leave/@pointer-out events
That meant when we fired either of those events, typically it was with an empty intersections array, and the events would never get propagated to the object that needed it.
Now they do, and this PR should fix #713

fix: Pointer Leave and Out events not being called

---

src/composables/useTresContextProvider/index.ts
src/core/loop.test.ts
src/core/loop.ts

closes #743
As discussed on Discord.

fix(loop/useTresReady): add setReady

---

docs/.vitepress/theme/components/LocalOrbitControls.vue
docs/.vitepress/theme/components/LoveVueThreeJS.vue
docs/advanced/caveats.md
docs/advanced/performance.md
docs/api/composables.md
docs/blog/announcing-v-3-1-0.md
docs/cookbook/basic-animations.md
docs/cookbook/groups.md

Supports #778
This PR changes `ref(aTresObject)` to `shallowRef(aTresObject)` in the English docs.

docs(en): change TresObject refs to shallowRefs

---

src/devtools/plugin.ts
src/utils/is.ts
src/utils/perf.ts

fix: 792 directionallighthelpers breaks devtools

---

docs/.vitepress/theme/components/HomeSponsors.vue

Happened to [spot this on Twitter](https://x.com/Cody_J_Bennett/status/1847053838400082213), and that no one else had fixed it yet.

docs: Correct sponsor name

---

src/types/index.ts

This PR adds the definition of primitive components to the global augmentation 
Closes #895

feat: extend GlobalComponents interface to include 'primitive' component type

---

src/utils/is.test.ts
src/utils/is.ts

Several `is` methods contain a short-circuiting operand. It evaluates `'bar' in foo` before checking `foo.bar`. E.g.:
```ts
return obj(u) && 'isFog' in u && !!(u.isFog)
```
This operand was included only to satisfy the ts linter/compiler. It no longer requires the operand.
Remove the `'bar' in foo` operands.
There is a lot of repetition between tests and tests are long to write.
Refactor tests down to a single statement per tested function. E.g.:
```ts
test(is.arr, ARRAYS)
```
Some `is` functions have no tests, e.g. `is.arr`.
Add tests for untested functions.
A few `is` methods are missing [type predicates](https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates).
Add the missing type predicates.

refactor(is): remove check for in, add tests

---

src/utils/index.ts

This reverts commit 790bbe8b68b4e37e35de7527863c9b5657b1144e.

fix: revert typescript changes for use dpr

---

src/utils/primitive/createRetargetingProxy.ts

This reverts commit 6d8e742646618bbf40b192bfe5dafa376f8780fe.

fix: revert improve type safety in retargeting proxy setter

---

docs/cookbook/tweakpane.md

It looks like the maintainer of Tweakpane has changed something in the organisation and how the link for the documentation Github pages is created. 
PS: Since it's such a small change I did not create a Github issue for this change.

docs: correct link to tweakpane in english docs

---

package.json
vite.config.ts

BREAKING CHANGE: Tres is now ESM only
- Removed UMD build configuration from package.json and adjusted exports to only include ES module.
- Updated vite.config.ts to specify the output format as ES, enhancing compatibility with modern module systems.
Closes #947

feat!: drop umd bundling

---

src/index.ts

- Added export for the logger utility from './utils/logger' to enhance logging capabilities across the ecosystem

fix: export logger utils

---

src/composables/useCamera/index.ts
src/composables/useTexture/index.ts
src/composables/useTresEventManager/index.ts
src/core/nodeOps.ts
src/devtools/plugin.ts
src/utils/index.ts
src/utils/is.test.ts
src/utils/is.ts

- Changed import statements in various files to directly import specific utility functions from './utils/is' instead of importing the entire module.
- This improves clarity and reduces potential namespace conflicts, ensuring that only the necessary functions are imported for use.
- Updated related logic in composables and core operations to utilize the new import structure for better maintainability.

chore: refactor-is-utils

---

package.json
playground/vue/package.json
playground/vue/vite.config.ts
pnpm-lock.yaml
src/devtools/plugin.ts

- Upgraded @vue/devtools-api from version 6.6.3 to 7.7.2 for improved functionality.
- Updated @tresjs/cientos dependency to a specific version hosted at a new URL for better version control.
- Enabled Vue DevTools in the Vite configuration for enhanced development experience.
- Adjusted the homepage link in the devtools plugin for accurate documentation reference.

feat: 974-vue-devtools-api-v7

---

src/components/TresCanvas.vue
src/composables/useTresContextProvider/index.ts
src/devtools/plugin.ts
src/devtools/setupDevtools.ts

- Moved the `registerTresDevtools` import in `TresCanvas.vue` to improve clarity and ensure proper registration of devtools.
- Renamed `setupDevtools` to `setupTresDevtools` in `setupDevtools.ts` for consistency with the new naming convention.
- Updated the `registerTresDevtools` function in `plugin.ts` to call the renamed `setupTresDevtools`, ensuring proper integration of the devtools setup.
- Removed the unused `setupDevtools` call from `useTresContextProvider` to streamline the context provider logic.

refactor: reorganize devtools setup and imports

---

src/core/nodeOps.test.ts
src/core/nodeOps.ts
src/utils/is.ts

Hardens inference in `patchProp`, where unsafe property access was permitted before. This aligns with R3F v9.
This fixes edge cases like https://github.com/pmndrs/koota/issues/58, where inference can be fooled into breaking setters for non-atomic values.

fix(patchProp): harden props inference

---

playground/vue/src/pages/advanced/webGPU/HologramCube.vue
playground/vue/src/pages/advanced/webGPU/index.vue
playground/vue/src/router/routes/advanced.ts
src/components/TresCanvas.vue
src/composables/useRenderer/useRendererManager.ts
src/composables/useTres/index.ts
src/composables/useTresContextProvider/index.ts
src/devtools/inspectorHandlers.ts

This PR adds native WebGPU support to TresJS, allowing for better performance and modern rendering capabilities. The changes include:
- Added WebGPU renderer support alongside existing WebGL renderer
- Improved renderer initialization with proper type handling
- Enhanced scene graph inspection capabilities for both WebGL and WebGPU contexts
- Added proper cleanup and context loss handling for both renderers
- Modified renderer manager to handle both WebGL and WebGPU renderers
- Updated type definitions to support both renderer types
- Improved inspector tools to work with both rendering backends
- Added proper initialization for WebGPU context
To enable WebGPU is as simple as: 
```ts
<script setup lang="ts">
const createWebGPURenderer = (ctx: TresRendererSetupContext) => {
const renderer …
```

feat: webgpu native support

---

docs/app/composables/useNavigation.ts

@Tinoooo found out that the `active` property is necessary for the categories' top menu to detect the state when navigating subpages

revert(docs): revert active navigation change

---

docs/content/1.getting-started/4.upgrade-guide.md

- Modified the usage section to reflect that the `useTexture` composable now returns a reactive state along with a loading state, enhancing clarity for users.
- Updated the import statement to align with the new structure of the TresJS core library.

docs: update upgrade guide for useTexture composable changes

---

docs/content/1.getting-started/3.your-first-scene.md

Hey There!
This is my first (and hopefully one of many) contributions.
I was following the tutorial and I noticed that there is a small issue in the code sample - I believe the `:position` from the previous step was missing as without it the Donut is in the middle of the Grid helper while it should be above it to make it look the same as in the demo :)

docs: Update Your First Scene
